/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calculate_H
#define calculate_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "plus_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class calculateIf {
 public:
  virtual ~calculateIf() {}
  virtual int32_t plus(const int32_t a, const int32_t b) = 0;
};

class calculateIfFactory {
 public:
  typedef calculateIf Handler;

  virtual ~calculateIfFactory() {}

  virtual calculateIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(calculateIf* /* handler */) = 0;
};

class calculateIfSingletonFactory : virtual public calculateIfFactory {
 public:
  calculateIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<calculateIf>& iface) : iface_(iface) {}
  virtual ~calculateIfSingletonFactory() {}

  virtual calculateIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(calculateIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<calculateIf> iface_;
};

class calculateNull : virtual public calculateIf {
 public:
  virtual ~calculateNull() {}
  int32_t plus(const int32_t /* a */, const int32_t /* b */) {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _calculate_plus_args__isset {
  _calculate_plus_args__isset() : a(false), b(false) {}
  bool a :1;
  bool b :1;
} _calculate_plus_args__isset;

class calculate_plus_args {
 public:

  calculate_plus_args(const calculate_plus_args&);
  calculate_plus_args& operator=(const calculate_plus_args&);
  calculate_plus_args() : a(0), b(0) {
  }

  virtual ~calculate_plus_args() throw();
  int32_t a;
  int32_t b;

  _calculate_plus_args__isset __isset;

  void __set_a(const int32_t val);

  void __set_b(const int32_t val);

  bool operator == (const calculate_plus_args & rhs) const
  {
    if (!(a == rhs.a))
      return false;
    if (!(b == rhs.b))
      return false;
    return true;
  }
  bool operator != (const calculate_plus_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const calculate_plus_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class calculate_plus_pargs {
 public:


  virtual ~calculate_plus_pargs() throw();
  const int32_t* a;
  const int32_t* b;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _calculate_plus_result__isset {
  _calculate_plus_result__isset() : success(false) {}
  bool success :1;
} _calculate_plus_result__isset;

class calculate_plus_result {
 public:

  calculate_plus_result(const calculate_plus_result&);
  calculate_plus_result& operator=(const calculate_plus_result&);
  calculate_plus_result() : success(0) {
  }

  virtual ~calculate_plus_result() throw();
  int32_t success;

  _calculate_plus_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const calculate_plus_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const calculate_plus_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const calculate_plus_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _calculate_plus_presult__isset {
  _calculate_plus_presult__isset() : success(false) {}
  bool success :1;
} _calculate_plus_presult__isset;

class calculate_plus_presult {
 public:


  virtual ~calculate_plus_presult() throw();
  int32_t* success;

  _calculate_plus_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class calculateClient : virtual public calculateIf {
 public:
  calculateClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  calculateClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t plus(const int32_t a, const int32_t b);
  void send_plus(const int32_t a, const int32_t b);
  int32_t recv_plus();
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class calculateProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<calculateIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (calculateProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_plus(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  calculateProcessor(::apache::thrift::stdcxx::shared_ptr<calculateIf> iface) :
    iface_(iface) {
    processMap_["plus"] = &calculateProcessor::process_plus;
  }

  virtual ~calculateProcessor() {}
};

class calculateProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  calculateProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< calculateIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< calculateIfFactory > handlerFactory_;
};

class calculateMultiface : virtual public calculateIf {
 public:
  calculateMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<calculateIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~calculateMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<calculateIf> > ifaces_;
  calculateMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<calculateIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t plus(const int32_t a, const int32_t b) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->plus(a, b);
    }
    return ifaces_[i]->plus(a, b);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class calculateConcurrentClient : virtual public calculateIf {
 public:
  calculateConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  calculateConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t plus(const int32_t a, const int32_t b);
  int32_t send_plus(const int32_t a, const int32_t b);
  int32_t recv_plus(const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
