/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef plus_CONSTANTS_H
#define plus_CONSTANTS_H

#include "plus_types.h"



class plusConstants {
 public:
  plusConstants();

};

extern const plusConstants g_plus_constants;



#endif
