/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef room_opt_CONSTANTS_H
#define room_opt_CONSTANTS_H

#include "room_opt_types.h"



class room_optConstants {
 public:
  room_optConstants();

};

extern const room_optConstants g_room_opt_constants;



#endif
