/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "room_opt_constants.h"



const room_optConstants g_room_opt_constants;

room_optConstants::room_optConstants() {
}



